
target:
	g++ example1.cpp -O3 -g -o a.out

nonOp:
	g++ example1.cpp -g -o a.out

#Instructions with tools

#time_ex:
#	time ./a.out

#callgrind:
#	valgrind --tool=callgrind --dump-line=yes ./a.out

#callgrind_read:
#	callgrind_annotate --auto=yes callgrind.out.*